import type {
  AccountRecord,
  AuditLogRecord,
  ConsumptionRecord,
  CreditEntryRecord,
  FinanceProfileRecord,
  RechargeAdjustmentLedger,
  SpecialRecord,
} from "./types";

export const accounts: AccountRecord[] = [
  {
    id: "USR-10001",
    accountType: "用户",
    accountName: "林舟",
    contact: "138****3261",
    status: "正常",
    ownerName: "林舟",
    planName: "创作专业版",
    planPointsBalance: 1280,
    rechargePointsBalance: 680,
    giftPointsBalance: 120,
    invoiceTitle: "/",
    taxNumber: "/",
    dataSource: "系统同步",
    activeMonths: ["2026-07", "2026-08"],
  },
  {
    id: "TEAM-20001",
    accountType: "团队",
    accountName: "知行文化创作团队",
    contact: "185****0092",
    status: "正常",
    ownerName: "周知行",
    planName: "团队专业版",
    planPointsBalance: 8600,
    rechargePointsBalance: 24600,
    giftPointsBalance: 3180,
    invoiceTitle: "知行文化传播有限公司",
    taxNumber: "91510100MA****8R",
    dataSource: "系统同步",
    activeMonths: ["2026-07", "2026-08"],
  },
  {
    id: "TEAM-20002",
    accountType: "团队",
    accountName: "成都两只鸭创作团队",
    contact: "028-****7715",
    status: "正常",
    ownerName: "杨小满",
    planName: "团队专业版",
    planPointsBalance: 32000,
    rechargePointsBalance: 48600,
    giftPointsBalance: 7600,
    invoiceTitle: "成都两只鸭文化科技有限公司",
    taxNumber: "91510107MA****5W",
    dataSource: "系统同步",
    activeMonths: ["2026-07", "2026-08"],
  },
  {
    id: "USR-10002",
    accountType: "用户",
    accountName: "陈帆",
    contact: "177****3088",
    status: "正常",
    ownerName: "陈帆",
    planName: "创作基础版",
    planPointsBalance: 380,
    rechargePointsBalance: 0,
    giftPointsBalance: 50,
    invoiceTitle: "/",
    taxNumber: "/",
    dataSource: "系统同步",
    activeMonths: ["2026-07"],
  },
  {
    id: "TEAM-20003",
    accountType: "团队",
    accountName: "星河工作室",
    contact: "186****9017",
    status: "到期停用",
    ownerName: "赵星河",
    planName: "团队版（已到期）",
    planPointsBalance: 0,
    rechargePointsBalance: 0,
    giftPointsBalance: 0,
    invoiceTitle: "/",
    taxNumber: "/",
    dataSource: "系统同步",
    activeMonths: ["2026-07"],
  },
];

export const financeProfiles: FinanceProfileRecord[] = [
  {
    id: "FIN-0001",
    customerType: "企业",
    customerName: "成都两只鸭文化科技有限公司",
    unifiedCreditCode: "91510107MA****5W",
    contactName: "杨小满",
    contactPhone: "028-****7715",
    accountStatus: "正常",
    contractNo: "HT-2026-017",
    serviceStart: "2026-01-01",
    serviceEnd: "2026-12-31",
    packageCycle: "年",
    contractPrepaidCap: 120000,
    unitPriceStandard: "10 元 / 调用",
    invoiceNeeded: "是",
    historicalInvoicedAmount: 32000,
    uninvoicedPrepaidBalance: 18000,
    linkedAccountIds: ["TEAM-20002", "USR-10002"],
    linkedAccountNames: ["成都两只鸭创作团队", "陈帆"],
    source: "人工维护",
    operator: "Wsq",
    lastModifiedBy: "Wsq",
    updatedAt: "2026-07-31 14:26:00",
    recordStatus: "有效",
  },
  {
    id: "FIN-0002",
    customerType: "企业",
    customerName: "知行文化传播有限公司",
    unifiedCreditCode: "91510100MA****8R",
    contactName: "周知行",
    contactPhone: "185****0092",
    accountStatus: "正常",
    contractNo: "HT-2026-021",
    serviceStart: "2026-07-01",
    serviceEnd: "2027-06-30",
    packageCycle: "年",
    contractPrepaidCap: 80000,
    unitPriceStandard: "20,000 元 / 年",
    invoiceNeeded: "是",
    historicalInvoicedAmount: 20000,
    uninvoicedPrepaidBalance: 0,
    linkedAccountIds: ["TEAM-20001"],
    linkedAccountNames: ["知行文化创作团队"],
    source: "人工维护",
    operator: "财务管理员",
    lastModifiedBy: "财务管理员",
    updatedAt: "2026-07-30 10:18:00",
    recordStatus: "有效",
  },
  {
    id: "FIN-0003",
    customerType: "个人",
    customerName: "林舟",
    unifiedCreditCode: "/",
    contactName: "林舟",
    contactPhone: "138****3261",
    accountStatus: "正常",
    contractNo: "/",
    serviceStart: "/",
    serviceEnd: "/",
    packageCycle: "月",
    contractPrepaidCap: "/",
    unitPriceStandard: "/",
    invoiceNeeded: "否",
    historicalInvoicedAmount: "/",
    uninvoicedPrepaidBalance: "/",
    linkedAccountIds: ["USR-10001"],
    linkedAccountNames: ["林舟"],
    source: "人工维护",
    operator: "财务管理员",
    lastModifiedBy: "财务管理员",
    updatedAt: "2026-07-31 14:30:00",
    recordStatus: "有效",
  },
];

export const creditEntries: CreditEntryRecord[] = [
  {
    id: "CR-20260721-001",
    recordSource: "后台充值积分调整",
    accountId: "TEAM-20002",
    accountName: "成都两只鸭创作团队",
    accountType: "团队",
    financeProfileId: "FIN-0001",
    financeProfileName: "成都两只鸭文化科技有限公司",
    customerType: "企业",
    month: "2026-07",
    businessNature: "线下购买",
    actualAmount: "/",
    giftAmount: "/",
    paymentMethod: "/",
    paymentReference: "/",
    discountType: "/",
    activityBatch: "/",
    receiptStatus: "/",
    contractNo: "HT-2026-017",
    planName: "/",
    planPoints: 0,
    rechargePoints: 50000,
    giftPoints: 0,
    pointsLedgerId: "CR-20260721-001",
    pointsDeliveryStatus: "已发放",
    occurredAt: "2026-07-21 10:36:22",
    operator: "Wsq",
    status: "有效",
    reason: "补充业务所需充值积分",
    source: "系统同步",
    lastModifiedBy: "/",
    updatedAt: "2026-07-21 10:36:22",
  },
  {
    id: "ORD-20260719-014",
    recordSource: "线上充值订单",
    accountId: "TEAM-20001",
    accountName: "知行文化创作团队",
    accountType: "团队",
    financeProfileId: "FIN-0002",
    financeProfileName: "知行文化传播有限公司",
    customerType: "企业",
    month: "2026-07",
    businessNature: "线上购买",
    actualAmount: 20000,
    giftAmount: "/",
    paymentMethod: "微信",
    paymentReference: "WX202607190866",
    discountType: "活动赠额",
    activityBatch: "SUMMER-2026",
    receiptStatus: "已收款",
    contractNo: "HT-2026-021",
    planName: "/",
    planPoints: 0,
    rechargePoints: 20000,
    giftPoints: 2600,
    pointsLedgerId: "SYS-PT-20260719-014",
    pointsDeliveryStatus: "已发放",
    occurredAt: "2026-07-19 16:08:11",
    operator: "系统",
    status: "有效",
    reason: "/",
    source: "系统同步",
    lastModifiedBy: "/",
    updatedAt: "2026-07-19 16:08:11",
  },
  {
    id: "ORD-20260717-021",
    recordSource: "线上充值订单",
    accountId: "USR-10001",
    accountName: "林舟",
    accountType: "用户",
    financeProfileId: "FIN-0003",
    financeProfileName: "林舟",
    customerType: "个人",
    month: "2026-07",
    businessNature: "线上购买",
    actualAmount: 1999,
    giftAmount: "/",
    paymentMethod: "支付宝",
    paymentReference: "ALI202607175102",
    discountType: "普通充值",
    activityBatch: "/",
    receiptStatus: "已收款",
    contractNo: "/",
    planName: "创作专业版",
    planPoints: 2000,
    rechargePoints: 0,
    giftPoints: 200,
    pointsLedgerId: "SYS-PT-20260717-021",
    pointsDeliveryStatus: "已发放",
    occurredAt: "2026-07-17 09:52:04",
    operator: "系统",
    status: "有效",
    reason: "/",
    source: "系统同步",
    lastModifiedBy: "/",
    updatedAt: "2026-07-17 09:52:04",
  },
  {
    id: "PLAN-20260715-006",
    recordSource: "后台套餐变更",
    accountId: "USR-10002",
    accountName: "陈帆",
    accountType: "用户",
    financeProfileId: "FIN-0001",
    financeProfileName: "成都两只鸭文化科技有限公司",
    customerType: "企业",
    month: "2026-07",
    businessNature: "免费升级",
    actualAmount: "/",
    giftAmount: "/",
    paymentMethod: "/",
    paymentReference: "/",
    discountType: "/",
    activityBatch: "/",
    receiptStatus: "/",
    contractNo: "HT-2026-017",
    planName: "创作基础版",
    planPoints: 500,
    rechargePoints: 0,
    giftPoints: 0,
    pointsLedgerId: "PLAN-20260715-006",
    pointsDeliveryStatus: "已发放",
    occurredAt: "2026-07-15 13:29:50",
    operator: "Wsq",
    status: "有效",
    reason: "体验活动免费升级",
    source: "系统同步",
    lastModifiedBy: "/",
    updatedAt: "2026-07-15 13:29:50",
  },
];

export const consumptions: ConsumptionRecord[] = [
  {
    id: "PTXN-0721-901",
    accountId: "TEAM-20002",
    accountName: "成都两只鸭创作团队",
    accountType: "团队",
    financeProfileId: "FIN-0001",
    financeProfileName: "成都两只鸭文化科技有限公司",
    customerType: "企业",
    month: "2026-07",
    occurredAt: "2026-07-21 12:05:16",
    scene: "视频生成",
    service: "Veo 3 · 1080P",
    planPoints: 1200,
    rechargePoints: 860,
    giftPoints: 140,
    principalDeductionAmount: "/",
    giftDeductionAmount: "/",
    billingUnitPrice: "/",
    measurementBasis: "生成 1 次",
    contractNo: "HT-2026-017",
    relatedType: "任务",
    relatedId: "781fdc1b-12f8-4da9-a112-9811200f6c52",
    status: "消耗成功",
    source: "系统同步",
    operator: "系统",
    lastModifiedBy: "/",
    updatedAt: "2026-07-21 12:05:16",
    recordStatus: "有效",
  },
  {
    id: "PTXN-0720-842",
    accountId: "TEAM-20001",
    accountName: "知行文化创作团队",
    accountType: "团队",
    financeProfileId: "FIN-0002",
    financeProfileName: "知行文化传播有限公司",
    customerType: "企业",
    month: "2026-07",
    occurredAt: "2026-07-20 18:42:09",
    scene: "图片生成",
    service: "Seedream 4.0",
    planPoints: 326,
    rechargePoints: 120,
    giftPoints: 0,
    principalDeductionAmount: "/",
    giftDeductionAmount: "/",
    billingUnitPrice: "/",
    measurementBasis: "生成 4 张",
    contractNo: "HT-2026-021",
    relatedType: "任务",
    relatedId: "2b77fa76-5fa8-41f7-a075-9805349183d1",
    status: "消耗成功",
    source: "系统同步",
    operator: "系统",
    lastModifiedBy: "/",
    updatedAt: "2026-07-20 18:42:09",
    recordStatus: "有效",
  },
  {
    id: "PTXN-0718-730",
    accountId: "USR-10001",
    accountName: "林舟",
    accountType: "用户",
    financeProfileId: "FIN-0003",
    financeProfileName: "林舟",
    customerType: "个人",
    month: "2026-07",
    occurredAt: "2026-07-18 22:10:35",
    scene: "视频生成",
    service: "Kling 2.1",
    planPoints: 77,
    rechargePoints: 24,
    giftPoints: 10,
    principalDeductionAmount: "/",
    giftDeductionAmount: "/",
    billingUnitPrice: "/",
    measurementBasis: "生成 1 次",
    contractNo: "/",
    relatedType: "任务",
    relatedId: "7cd6d83a-18b7-48fa-9874-978310359f6a",
    status: "消耗成功",
    source: "系统同步",
    operator: "系统",
    lastModifiedBy: "/",
    updatedAt: "2026-07-18 22:10:35",
    recordStatus: "有效",
  },
  {
    id: "PTXN-0716-621",
    accountId: "USR-10002",
    accountName: "陈帆",
    accountType: "用户",
    financeProfileId: "FIN-0001",
    financeProfileName: "成都两只鸭文化科技有限公司",
    customerType: "企业",
    month: "2026-07",
    occurredAt: "2026-07-16 14:03:20",
    scene: "音频生成",
    service: "语音合成",
    planPoints: 144,
    rechargePoints: 0,
    giftPoints: 0,
    principalDeductionAmount: "/",
    giftDeductionAmount: "/",
    billingUnitPrice: "/",
    measurementBasis: "音频 32 秒",
    contractNo: "HT-2026-017",
    relatedType: "任务",
    relatedId: "185947f3-a9e1-46d1-8cdd-9760256c5fe8",
    status: "消耗成功",
    source: "系统同步",
    operator: "系统",
    lastModifiedBy: "/",
    updatedAt: "2026-07-16 14:03:20",
    recordStatus: "有效",
  },
];

export const specialRecords: SpecialRecord[] = [
  {
    id: "SPC-20260725-008",
    accountId: "TEAM-20001",
    accountName: "知行文化创作团队",
    accountType: "团队",
    financeProfileId: "FIN-0002",
    financeProfileName: "知行文化传播有限公司",
    customerType: "企业",
    month: "2026-07",
    type: "退款业务",
    businessNature: "退款扣回",
    occurredAt: "2026-07-25 15:38:20",
    planPoints: 0,
    rechargePoints: -2260,
    giftPoints: 0,
    relatedRecordType: "充值订单",
    relatedRecordId: "ORD-20260719-014",
    pointsLedgerId: "ADJ-REFUND-0725-008",
    handlingStatus: "退款已完成",
    fundStatus: "已退款",
    refundAmount: 2000,
    refundDate: "2026-07-25",
    transferReference: "BANK-REFUND-0725-008",
    refundReason: "服务终止",
    refundReasonNote: "/",
    refundEvidence: "退款审批单.pdf",
    reason: "退款后扣回对应充值积分",
    operator: "Wsq",
    source: "系统同步",
    lastModifiedBy: "财务管理员",
    updatedAt: "2026-07-25 15:42:08",
    status: "有效",
  },
  {
    id: "SPC-20260723-015",
    accountId: "TEAM-20003",
    accountName: "星河工作室",
    accountType: "团队",
    financeProfileId: "/",
    financeProfileName: "/",
    customerType: "/",
    month: "2026-07",
    type: "过期清零",
    businessNature: "自动过期清零",
    occurredAt: "2026-07-23 09:00:00",
    planPoints: 0,
    rechargePoints: 0,
    giftPoints: -329,
    relatedRecordType: "/",
    relatedRecordId: "/",
    pointsLedgerId: "CLEAR-0723-015",
    handlingStatus: "无需处理",
    fundStatus: "不涉及资金",
    refundAmount: "/",
    refundDate: "/",
    transferReference: "/",
    refundReason: "/",
    refundReasonNote: "/",
    refundEvidence: "/",
    reason: "团队到期后清理过期赠送积分",
    operator: "系统",
    source: "系统同步",
    lastModifiedBy: "/",
    updatedAt: "2026-07-23 09:00:00",
    status: "有效",
  },
  {
    id: "SPC-20260719-011",
    accountId: "TEAM-20002",
    accountName: "成都两只鸭创作团队",
    accountType: "团队",
    financeProfileId: "FIN-0001",
    financeProfileName: "成都两只鸭文化科技有限公司",
    customerType: "企业",
    month: "2026-07",
    type: "调账 / 冲红",
    businessNature: "系统调账或冲红",
    occurredAt: "2026-07-19 11:45:22",
    planPoints: 48,
    rechargePoints: 0,
    giftPoints: 0,
    relatedRecordType: "积分流水",
    relatedRecordId: "PTXN-0718-728",
    pointsLedgerId: "ADJ-0719-011",
    handlingStatus: "无需处理",
    fundStatus: "不涉及资金",
    refundAmount: "/",
    refundDate: "/",
    transferReference: "/",
    refundReason: "/",
    refundReasonNote: "/",
    refundEvidence: "/",
    reason: "失败任务积分消耗冲回",
    operator: "Wsq",
    source: "系统同步",
    lastModifiedBy: "/",
    updatedAt: "2026-07-19 11:45:22",
    status: "有效",
  },
  {
    id: "SPC-20260708-003",
    accountId: "USR-10001",
    accountName: "林舟",
    accountType: "用户",
    financeProfileId: "FIN-0003",
    financeProfileName: "林舟",
    customerType: "个人",
    month: "2026-07",
    type: "作废 / 取消未生效充值订单",
    businessNature: "未支付取消",
    occurredAt: "2026-07-08 20:19:01",
    planPoints: 0,
    rechargePoints: 0,
    giftPoints: 0,
    relatedRecordType: "充值订单",
    relatedRecordId: "ORD-20260708-033",
    pointsLedgerId: "/",
    handlingStatus: "无需处理",
    fundStatus: "不涉及资金",
    refundAmount: "/",
    refundDate: "/",
    transferReference: "/",
    refundReason: "/",
    refundReasonNote: "/",
    refundEvidence: "/",
    reason: "付款未完成，订单自动取消",
    operator: "系统",
    source: "系统同步",
    lastModifiedBy: "/",
    updatedAt: "2026-07-08 20:19:01",
    status: "有效",
  },
];

export const rechargeAdjustmentLedgers: RechargeAdjustmentLedger[] = [
  {
    id: "CR-20260721-001",
    accountId: "TEAM-20002",
    accountName: "成都两只鸭创作团队",
    accountType: "团队",
    direction: "增加",
    businessNature: "线下购买",
    delta: 50000,
    balanceBefore: 0,
    balanceAfter: 50000,
    source: "后台手动调整",
    reason: "补充业务所需充值积分",
    operator: "Wsq",
    occurredAt: "2026-07-21 10:36:22",
  },
  {
    id: "CR-20260718-004",
    accountId: "USR-10001",
    accountName: "林舟",
    accountType: "用户",
    direction: "扣减",
    businessNature: "纠错扣减",
    delta: -400,
    balanceBefore: 1080,
    balanceAfter: 680,
    source: "后台手动调整",
    reason: "录入错误，反向调整",
    operator: "Wsq",
    occurredAt: "2026-07-18 15:20:08",
  },
  {
    id: "ADJ-REFUND-0725-008",
    accountId: "TEAM-20001",
    accountName: "知行文化创作团队",
    accountType: "团队",
    direction: "扣减",
    businessNature: "退款扣回",
    delta: -2260,
    balanceBefore: 26740,
    balanceAfter: 24480,
    source: "后台手动调整",
    reason: "退款后扣回对应充值积分",
    operator: "Wsq",
    occurredAt: "2026-07-25 15:38:20",
  },
];

export const initialAuditLogs: AuditLogRecord[] = [
  {
    id: "AUD-001",
    recordId: "FIN-0001",
    action: "创建",
    operator: "Wsq",
    occurredAt: "2026-07-10 10:18:00",
    detail: "创建财务档案并关联成都两只鸭创作团队、陈帆",
  },
  {
    id: "AUD-002",
    recordId: "SPC-20260725-008",
    action: "修改",
    operator: "财务管理员",
    occurredAt: "2026-07-25 15:42:08",
    detail: "补充线下对公退款资料，资金状态变为已退款",
  },
];
